/**
 * javascript-obfuscator 配置，详细配置说明见官方文档
 */
module.exports = {
  compact: true,
  // controlFlowFlattening: false,
  // controlFlowFlatteningThreshold: 0.75,
  // deadCodeInjection: false,
  // deadCodeInjectionThreshold: 0.4,
  // debugProtection: false,
  // debugProtectionInterval: 0,
  // disableConsoleOutput: false,
  // domainLock: [],
  // domainLockRedirectUrl: "about:blank",
  // forceTransformStrings: [],
  // identifierNamesCache: null,
  // identifierNamesGenerator: "hexadecimal",
  // identifiersDictionary: [],
  // identifiersPrefix: "",
  // ignoreImports: false,
  // inputFileName: "",
  log: true,
  // numbersToExpressions: false,
  optionsPreset: "default",
  // renameGlobals: false,
  // renameProperties: false,
  // renamePropertiesMode: "safe",
  // reservedNames: [],
  // reservedStrings: [],
  // seed: 0,
  // selfDefending: false,
  simplify: true,
  // sourceMap: false,
  // sourceMapBaseUrl: "",
  // sourceMapFileName: "",
  // sourceMapMode: "separate",
  // sourceMapSourcesMode: "sources-content",
  // splitStrings: true,
  // splitStringsChunkLength: 10,
  // stringArray: true,
  // stringArrayCallsTransform: false,
  // stringArrayCallsTransformThreshold: 0.5,
  // stringArrayEncoding: [],
  // stringArrayIndexesType: [
  //   "hexadecimal-number"
  // ],
  // stringArrayIndexShift: false,
  // stringArrayRotate: false,
  // stringArrayShuffle: false,
  // stringArrayWrappersCount: 1,
  // stringArrayWrappersChainedCalls: false,
  // stringArrayWrappersParametersMaxCount: 2,
  // stringArrayWrappersType: "variable",
  // stringArrayThreshold: 0.75,
  target: "node",
  transformObjectKeys: false,
  unicodeEscapeSequence: true
}